BanqueTardiApp/Models/Client.cs
using BanqueTardiApp.Validations;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace BanqueTardiApp.Models
{
    public class Client
    {
        public Client() 
        {
            Comptes = new List<CompteBancaire>();
            NbDecouverts = 0;
        }
        [Key]
        public required string Code { get; set; }

        [Required(ErrorMessage = "Le nom est requis.")]
        [MaxLength(150)]
        [Display(Name = "Nom")]
        public string Nom { get; set; }

        [Required(ErrorMessage = "Le prénom est requis.")]
        [MaxLength(150)]
        [Display(Name = "Prénom")]
        public string Prenom { get; set; }

        [Required(ErrorMessage = "La date de naissance est requise.")]
        [AgeMinimum(15, ErrorMessage = "L'âge minimum requis est 15 ans.")]
        [Display(Name = "Date de naissance")]
        public DateTime DateNaissance { get; set; } = DateTime.Now;

        [Required(ErrorMessage = "L'adresse est requise.")]
        [MaxLength(250)]
        [Display(Name = "Adresse")]
        public string Adresse { get; set; }

        [Required(ErrorMessage = "Le code postal est requis.")]
        [ZipCodeCA(ErrorMessage = "Le code postal doit être au format A1A 1A1.")]
        [Display(Name = "Code postal")]
        public string CodePostal { get; set; }

        [Required(ErrorMessage = "Le téléphone est requis.")]
        [Phone(ErrorMessage = "Ce numéro de téléphone n'est pas valide.")]
        [Display(Name = "Téléphone")]
        public string Telephone { get; set; }

        [Display(Name = "Nombre de comptes découverts")]
        public int NbDecouverts { get; set; }
        public ICollection<CompteBancaire>? Comptes { get; set; }

        [MaxLength(150)]
        [RequisPourMineur(ErrorMessage = "Le nom du parent est requis.")]
        [Display(Name = "Nom du parent")]
        public string? NomParent { get; set; }
        
        [RequisPourMineur(ErrorMessage = "Le téléphone du parent est requis.")]
        [Phone(ErrorMessage = "Ce numéro de téléphone n'est pas valide.")]
        [Display(Name = "Téléphone du parent")]
        public string? TelephoneParent { get; set; }
    }

}

BanqueTardiApp/Controllers/ClientsController.cs
using BanqueTardiApp.Donnees;
using BanqueTardiApp.Models;
using BanqueTardiApp.Services.Implementations;
using BanqueTardiApp.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BanqueTardiApp.Controllers
{
    public class ClientsController : Controller
    {
        private readonly IClientService _clientService;
        private readonly ICompteBancaireService _compteBancaireService;
        private readonly ITransactionService _transactionService;
        public ClientsController(IClientService clientService, ICompteBancaireService compteBancaireSerivce, ITransactionService transactionService)
        {
            _clientService = clientService;
            _compteBancaireService = compteBancaireSerivce;
            _transactionService = transactionService;
        }

        public async Task<IActionResult> Index(string? nomRechercher)
        {
            ViewData["Filtre"] = nomRechercher;

            var clients = await _clientService.RechercherListeClientsAsync(nomRechercher);

            return View(clients);
        }

        public async Task<IActionResult> Gerer(string? code)
        {
            var client = await _clientService.ObtenirClientParCodeAsync(code);

            var comptesBancaires = await _compteBancaireService.ObtenirListeComptesAsync(code);

            foreach (var compte in comptesBancaires)
            {
                compte.Transactions = await _transactionService.ObtenirDernieresTransactionsAsync(compte.NumeroCompte, 10);
            }

            if (client == null)
            {
                return NotFound($"Aucun client avec le code {code} n'a été trouvé.");
            }

            return View(client);
        }

        public async Task<IActionResult> Creer()
        {
            var client = await _clientService.CreerNouveauClientAsync();

            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Creer(Client client)
        {
            if (ModelState.IsValid)
            {
                bool resultat = await _clientService.EnregistrerNouveauClientAsync(client);

                if (resultat)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", "Une erreur est survenue lors de l'enregistrement du client.");
                }
            }

            return View(client);
        }

        public async Task<IActionResult> FicheDetaillee(string? code)
        {
            var client = await _clientService.ObtenirClientParCodeAsync(code);

            if (client == null)
            {
                return NotFound($"Impossible de trouver le client {code}");
            }

            return View(client);
        }

        public async Task<IActionResult> Modifier(string? code)
        {
            var client = await _clientService.ObtenirClientParCodeAsync(code);

            if (client == null)
            {
                return NotFound($"Impossible de trouver le client {code}");
            }

            return View(client);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Modifier(string? code, Client client)
        {
            if (ModelState.IsValid)
            {
                bool resultat = await _clientService.ModifierClientAsync(code, client);

                if (resultat)
                {
                    return RedirectToAction(nameof(Gerer), new {code = client.Code});
                }
                else
                {
                    ModelState.AddModelError("", "Une erreur est survenue lors de la modification du client.");
                }
            }

            return View(client);
        }

        public async Task<IActionResult> Supprimer(string? code)
        {
            var client = await _clientService.ObtenirClientParCodeAsync(code);

            if (client == null)
            {
                return NotFound($"Impossible de trouver le client {code}");
            }

            return View(client);
        }

        [HttpPost, ActionName("Supprimer")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmerSuppression(string? code, Client client)
        {
            bool resultat = await _clientService.SupprimerClientAsync(code, client);

            if (resultat)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("", "Une erreur est survenue lors de la suppression du client.");
                var clientASupprimer = await _clientService.ObtenirClientParCodeAsync(client?.Code);
                if (clientASupprimer == null)
                {
                    return NotFound();
                }
                return View("Supprimer", clientASupprimer);
            }
        }
    }
}

BanqueTardiApp/Controllers/CompteBancairesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BanqueTardiApp.Donnees;
using BanqueTardiApp.Models;
using BanqueTardiApp.Services.Interfaces;

namespace BanqueTardiApp.Controllers
{
    public class CompteBancairesController : Controller
    {
        private readonly ICompteBancaireService _compteBancaireService;

        public CompteBancairesController(ICompteBancaireService compteBancaireService)
        {
            _compteBancaireService = compteBancaireService;
        }

        public IActionResult Creer(string? clientCode)
        {
            var compte = _compteBancaireService.CreerNouveauCompte(clientCode);

            return View(compte);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Creer(CompteBancaire? compteBancaire)
        {
            if (ModelState.IsValid)
            {
                await _compteBancaireService.EnregistrerNouveauCompteAsync(compteBancaire);
                return RedirectToAction("Gerer", "Clients", new { code = compteBancaire?.ClientCode });

            }

            return View(compteBancaire);
        }

        public async Task<IActionResult> Modifier(string? noCompteBancaire)
        {
            var compteBancaire = await _compteBancaireService.ObtenirCompteParNumeroAsync(noCompteBancaire);

            if (compteBancaire == null)
            {
                return NotFound($"Impossible de trouver le compte {noCompteBancaire}");
            }

            ViewBag.ContientSeulementOuverture = await _compteBancaireService.PeutModifierCompteBancaire(noCompteBancaire);

            return View(compteBancaire);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Modifier(string? noCompte, CompteBancaire compteBancaire)
        {
            if (ModelState.IsValid)
            {
                bool resultat = await _compteBancaireService.ModifierCompteAsync(noCompte, compteBancaire);

                if (resultat)
                {
                    return RedirectToAction("Gerer", "Clients", new { code = compteBancaire?.ClientCode });
                }
                else
                {
                    ModelState.AddModelError("", "Une erreur est survenue lors de la modification du client.");
                }
            }

            return View(compteBancaire);
        }
    }
}

BanqueTardiApp/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BanqueTardiApp.Donnees;
using BanqueTardiApp.Models;
using BanqueTardiApp.Services.Interfaces;

namespace BanqueTardiApp.Controllers
{
    public class TransactionsController : Controller
    {
        private readonly ITransactionService _transactionService;
        private readonly ICompteBancaireService _compteBancaireService;

        public TransactionsController(ITransactionService transactionService, ICompteBancaireService compteBancaireService)
        {
            _transactionService = transactionService;
            _compteBancaireService = compteBancaireService;
        }

        public async Task<IActionResult> Historique(string? noCompteBancaire, TypeOperation? typeOperation = null)
        {
            var compteBancaire = await _compteBancaireService.ObtenirCompteParNumeroAsync(noCompteBancaire);

            if (compteBancaire == null)
            {
                return NotFound($"Aucun compte bancaire avec numero {noCompteBancaire} n'a été trouvé.");
            }

            var transactions = await _transactionService.ObtenirListeTransactionsAsync(noCompteBancaire);

            if (typeOperation.HasValue)
            {
                transactions = transactions.Where(t => t.TypeOperation == typeOperation.Value).ToList();
            }

            ViewBag.ClientCode = compteBancaire.ClientCode;
            ViewBag.NumeroCompte = compteBancaire.NumeroCompte;
            ViewBag.SelectedTypeOperation = typeOperation;

            return View(transactions);
        }

        public async Task<IActionResult> Creer(string? noCompteBancaire)
        {
            var transaction = await _transactionService.CreerNouvelleTransactionAsync(noCompteBancaire);

            return View(transaction);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Creer(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                var compteBancaire = await _compteBancaireService.ObtenirCompteParNumeroAsync(transaction.NumeroCompte);

                if (compteBancaire == null)
                {
                    ModelState.AddModelError("", "Le compte bancaire associé n'a pas été trouvé. Veuillez vérifier le numéro de compte.");
                    return View(transaction);
                }

                var (succes, messageErreur) = await _transactionService.EnregistrerNouvelleTransactionAsync(transaction);

                if (succes)
                {
                    return RedirectToAction("Gerer", "Clients", new { code = compteBancaire.ClientCode });
                }
                else
                {
                    ModelState.AddModelError("", messageErreur);
                }
            }

            transaction.CompteBancaire = await _compteBancaireService.ObtenirCompteParNumeroAsync(transaction.NumeroCompte);

            return View(transaction);
        }

    }
}

BanqueTardiApp/Views/Clients/Creer.cshtml
@model BanqueTardiApp.Models.Client

@{
    ViewData["Title"] = "Nouveau client";
}

<h1>Nouveau client</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Creer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" readonly="readonly" />
            </div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateNaissance" class="control-label"></label>
                <input asp-for="DateNaissance" class="form-control" id="DateNaissance" type="date" />
                <span asp-validation-for="DateNaissance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodePostal" class="control-label"></label>
                <input asp-for="CodePostal" class="form-control" />
                <span asp-validation-for="CodePostal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telephone" class="control-label"></label>
                <input asp-for="Telephone" class="form-control" />
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NomParent" class="control-label"></label>
                <input asp-for="NomParent" class="form-control" id="NomParent" disabled />
                <span asp-validation-for="NomParent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelephoneParent" class="control-label"></label>
                <input asp-for="TelephoneParent" class="form-control" id="TelephoneParent" disabled />
                <span asp-validation-for="TelephoneParent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Enregistrer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Liste des clients</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(document).ready(function () {
            const AGE_MINIMUM = 15;
            const AGE_MAXIMUM = 18;

            function configurerFormulaire() {

                var dateNaissance = $('#DateNaissance').val();
                var age = calculerAge(dateNaissance);

                if (age >= AGE_MINIMUM && age < AGE_MAXIMUM) {
                    $('#NomParent, #TelephoneParent').prop('disabled', false);
                } else {
                    $('#NomParent, #TelephoneParent').val('').prop('disabled', true);
                }
            }

            $('#DateNaissance').on('blur keyup change', configurerFormulaire);

            configurerFormulaire();
        });
    </script>
}

BanqueTardiApp/Views/Clients/FicheDetaillee.cshtml
@model BanqueTardiApp.Models.Client

@{
    ViewData["Title"] = "Fiche détaillée client";
}

<h1>Fiche détaillée</h1>

<div>
    <h4>Client</h4>
    <hr />
    <table class="table table-bordered">
        <tbody>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Nom)</th>
                <td>@Html.DisplayFor(model => model.Nom)</td>
            </tr>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Prenom)</th>
                <td>@Html.DisplayFor(model => model.Prenom)</td>
            </tr>
            <tr>
                <th>@Html.DisplayNameFor(model => model.DateNaissance)</th>
                <td>@Model.DateNaissance.ToLongDateString()</td>
            </tr>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Adresse)</th>
                <td>@Html.DisplayFor(model => model.Adresse)</td>
            </tr>
            <tr>
                <th>@Html.DisplayNameFor(model => model.CodePostal)</th>
                <td>@Html.DisplayFor(model => model.CodePostal)</td>
            </tr>
            <tr>
                <th>@Html.DisplayNameFor(model => model.NbDecouverts)</th>
                <td>@Html.DisplayFor(model => model.NbDecouverts)</td>
            </tr>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Telephone)</th>
                <td>@Html.DisplayFor(model => model.Telephone)</td>
            </tr>
            @if (!string.IsNullOrEmpty(Model.NomParent))
            {
                <tr>
                    <th>@Html.DisplayNameFor(model => model.NomParent)</th>
                    <td>@Html.DisplayFor(model => model.NomParent)</td>
                </tr>
            }
            @if (!string.IsNullOrEmpty(Model.TelephoneParent))
            {
                <tr>
                    <th>@Html.DisplayNameFor(model => model.TelephoneParent)</th>
                    <td>@Html.DisplayFor(model => model.TelephoneParent)</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <a asp-action="Gerer" asp-route-code="@Model.Code">Retourner à la gestion du client</a>
</div>

BanqueTardiApp/Views/Clients/Gerer.cshtml
@model BanqueTardiApp.Models.Client

@{
    ViewData["Title"] = "Gérer client";
}

<div class="container">
    <h2 class="mt-4">Gestion du client</h2>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered">
                <tr>
                    <th>Nom</th>
                    <td>@Model.Nom</td>
                </tr>
                <tr>
                    <th>Prénom</th>
                    <td>@Model.Prenom</td>
                </tr>
                <tr>
                    <th>Code</th>
                    <td>@Model.Code</td>
                </tr>
            </table>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-12 text-center">
            <a asp-action="FicheDetaillee" asp-route-code="@Model.Code" class="btn btn-link">Fiche détaillée</a>
            <a asp-action="Modifier" asp-route-code="@Model.Code" class="btn btn-link">Modifier</a>
            <a asp-action="Supprimer" asp-route-code="@Model.Code" class="btn btn-link">Supprimer</a>
            <a asp-controller="CompteBancaires" asp-action="Creer" asp-route-clientCode="@Model.Code" class="btn btn-link">Ajouter compte</a>
        </div>
    </div>

    @if (Model.Comptes != null)
    {
        <div>
            @foreach (var compte in Model.Comptes)
            {
                <div class="compte-container">
                    <div class="compte-header">
                        <div class="compte-info">

                            <span>
                                Compte:
                                @(compte.TypeCompte switch
                                {
                                    TypeCompte.Cheque => "Chèque",
                                    TypeCompte.Epargne => "Épargne",
                                    TypeCompte.Placement => "Placement garanti",
                                    _ => compte.TypeCompte.ToString()
                                })
                            </span>

                            <span>No Compte: @compte.NumeroCompte</span>
                        </div>
                        <div>
                            <a asp-action="Modifier" asp-controller="CompteBancaires" asp-route-noCompteBancaire="@compte.NumeroCompte" class="btn btn-link">Modifier</a>
                            <a asp-action="Historique" asp-controller="Transactions" asp-route-noCompteBancaire="@compte.NumeroCompte" class="btn btn-link">Historique</a>
                            <a asp-action="Creer" asp-controller="Transactions" asp-route-noCompteBancaire="@compte.NumeroCompte" class="btn btn-link">Ajouter opération</a>
                        </div>
                    </div>
                    <div class="mt-2">
                        <h4>10 dernières opérations</h4>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Type d'opération</th>
                                    <th>Montant</th>
                                    <th>Libellé</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var transaction in compte.Transactions)
                                {
                                    <tr>
                                        <td>@transaction.DateOperation.ToShortDateString()</td>
                                        <td>
                                            @(transaction.TypeOperation switch
                                            {
                                                TypeOperation.Debit => "Débit",
                                                TypeOperation.Credit => "Crédit",
                                                _ => transaction.TypeOperation.ToString()
                                            })
                                        </td>
                                        <td>@transaction.Montant</td>
                                        <td>@transaction.Libelle</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="compte-footer">
                        <span>Solde du compte : @Html.DisplayFor(m => compte.Solde)</span>
                    </div>
                </div>
                <hr />
            }
        </div>
    }
</div>

BanqueTardiApp/Views/Clients/Index.cshtml
@model IEnumerable<BanqueTardiApp.Models.Client>

@{
    ViewData["Title"] = "Liste client";
}

<h1>Liste des clients</h1>

<p>
    <a asp-action="Creer">Nouveau client</a>
</p>
<form method="get" action="@Url.Action("Index", "Clients")">
    <input type="text" name="nomRechercher" placeholder="Rechercher par nom" value="@ViewData["Filtre"]" />
    <button type="submit" class="btn btn-primary">Rechercher</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adresse)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model == null || !Model.Any())
        {
            <tr>
                <td colspan="3" style="font-weight: bold; font-size: 1.2em;" class="text-danger">
                    Aucun client ne correspond au nom recherché.
                </td>
            </tr>
        }
        else
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Prenom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Adresse)
                    </td>
                    <td>
                        <a asp-action="Gerer" asp-route-code="@item.Code">Gérer</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

BanqueTardiApp/Views/Clients/Modifier.cshtml
@model BanqueTardiApp.Models.Client

@{
    ViewData["Title"] = "Modifier client";
}

<h1>Modifier</h1>

<h4>Client</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Modifier">
            <input type="hidden" name="codeClient" value="@Model.Code" />

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Code" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateNaissance" class="control-label"></label>
                <input asp-for="DateNaissance" class="form-control" type="date" />
                <span asp-validation-for="DateNaissance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodePostal" class="control-label"></label>
                <input asp-for="CodePostal" class="form-control" />
                <span asp-validation-for="CodePostal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NbDecouverts" class="control-label"></label>
                <input asp-for="NbDecouverts" class="form-control" />
                <span asp-validation-for="NbDecouverts" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telephone" class="control-label"></label>
                <input asp-for="Telephone" class="form-control" />
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>

            <div class="form-group parent-prop">
                <label asp-for="NomParent" class="control-label"></label>
                <input asp-for="NomParent" class="form-control" />
                <span asp-validation-for="NomParent" class="text-danger"></span>
            </div>
            <div class="form-group parent-prop">
                <label asp-for="TelephoneParent" class="control-label"></label>
                <input asp-for="TelephoneParent" class="form-control" />
                <span asp-validation-for="TelephoneParent" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Enregistrer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Gerer" asp-route-code="@Model.Code">Retourner à la gestion du client</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            const AGE_MINIMUM = 15;
            const AGE_MAXIMUM = 18;

            function configurerFormulaire() {

                var dateNaissance = $('#DateNaissance').val();
                var age = calculerAge(dateNaissance);

                if (age >= AGE_MINIMUM && age < AGE_MAXIMUM) {
                    $('.parent-prop').show();
                } else {
                    $('.parent-prop').hide();
                }
            }

            $('#DateNaissance').on('blur keyup change', configurerFormulaire);

            configurerFormulaire();
        });
    </script>
}

BanqueTardiApp/Views/Clients/Supprimer.cshtml
@model BanqueTardiApp.Models.Client

@{
    ViewData["Title"] = "Supprimer client";
}

<h1>Supprimer</h1>

<h3>Êtes-vous sûr de vouloir supprimer ce client ?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Nom)</th>
            <td>@Html.DisplayFor(model => model.Nom)</td>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Prenom)</th>
            <td>@Html.DisplayFor(model => model.Prenom)</td>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(model => model.DateNaissance)</th>
            <td>@Model.DateNaissance.ToLongDateString()</td>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Adresse)</th>
            <td>@Html.DisplayFor(model => model.Adresse)</td>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(model => model.CodePostal)</th>
            <td>@Html.DisplayFor(model => model.CodePostal)</td>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(model => model.NbDecouverts)</th>
            <td>@Html.DisplayFor(model => model.NbDecouverts)</td>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Telephone)</th>
            <td>@Html.DisplayFor(model => model.Telephone)</td>
        </tr>
    </table>

    <form asp-action="Supprimer">
        <input type="hidden" name="code" value="@Model.Code" />
        <input type="submit" value="Supprimer" class="btn btn-danger" /> |
        <a asp-action="Gerer" asp-route-code="@Model.Code">Retourner à gestion du client</a>
    </form>
</div>